name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      run: #Asish987543
        docker build -t asishghosh9876/python-app:${{ github.run_number }} .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u asishghosh9876 --Asish987543-stdin
        docker push asishghosh9876/python-app:${{ github.run_number }}
